# Site settings
title: Nathan Shane
subtitle: Tbilisi-based web developer
description: >
  Nathan Shane is a Tbilisi-based web developer. He works part-time
  for JumpStart Georgia, a data-communication NGO, and also as a freelancer.
  His web skills include data scraping and full-stack application development
  in Rails.
url: 'http://nathanshane.me'
github_username: nwshane
timezone: Asia/Tbilisi

# Build settings
markdown: kramdown

gems:
  - octopress-debugger

# Default front matter
defaults:
-
  scope:
    path: "projects"
    type: "posts" # previously `page` in Jekyll 2.2.
  values:
    layout: "project" # overrides previous default layout
